#ifndef DELILAH_CONF_CONF
#define DELILAH_CONF_CONF

#include "util/units.h"

#define DELILAH_BAR0_LOC 0x10000000
#define DELILAH_BAR0_SIZE (32 * MiB)

#define DELILAH_DATA_LOC 0x12000000
#define DELILAH_DATA_SIZE (520 * MiB)

#define DELILAH_H2C_CHANNELS 4
#define DELILAH_C2H_CHANNELS 4

#endif
