#ifndef DELILAH_ERRORS
#define DELILAH_ERRORS

#define DELILAH_ERRORS_MEM_DEV 0x001
#define DELILAH_ERRORS_MEM_MMAP 0x002
#define DELILAH_ERRORS_IRQ_GPIO_FD 0x003
#define DELILAH_ERRORS_LOADER_ALLOC 0x004
#define DELILAH_ERRORS_INVALID_SLOT_TYPE 0x005

#endif
