#ifndef DELILAH_HERMES_OPCODES
#define DELILAH_HERMES_OPCODES

#define HERMES_OPCODE_REQUEST_SLOT 0x00
#define HERMES_OPCODE_RELEASE_SLOT 0x01
#define HERMES_OPCODE_EXECUTE_SLOT 0x80
#define HERMES_OPCODE_EXECUTE_SLOT_JIT 0x81

#endif
