#ifndef DELILAH_HERMES_OPCODES
#define DELILAH_HERMES_OPCODES

#define DELILAH_OPCODE_CLEAR_CACHE 0x50
#define DELILAH_OPCODE_CLEAR_STATE 0x51
#define HERMES_OPCODE_EXECUTE_SLOT 0x80
#define HERMES_OPCODE_EXECUTE_SLOT_JIT 0x81

#endif
