#ifndef DELILAH_HERMES_STATUS
#define DELILAH_HERMES_STATUS

#define HERMES_STATUS_SUCCESS 0x00
#define HERMES_STATUS_OUT_OF_SPACE 0x01
#define HERMES_STATUS_INVALID_PROG_SLOT 0x02
#define HERMES_STATUS_INVALID_DATA_SLOT 0x03
#define HERMES_STATUS_INVALID_ADDR 0x04
#define HERMES_STATUS_EBPF_ERROR 0x05
#define HERMES_STATUS_INVALID_OPCODE 0x06

#endif
