#ifndef DELILAH_HERMES_STATUS
#define DELILAH_HERMES_STATUS

#define HERMES_STATUS_SUCCESS 0x00
#define HERMES_STATUS_INVALID_ARGUMENT 0x01
#define HERMES_STATUS_EBPF_ERROR 0x02
#define HERMES_STATUS_INVALID_OPCODE 0x03

#endif
